import '~/styles/globals.css';

import Link from 'next/link';

import { CircleUserRound } from 'lucide-react';

import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuList,
  NavigationMenuLink,
} from '../components/ui/navigation-menu';

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
  DropdownMenuGroup,
  DropdownMenuItem,
} from '~/components/ui/dropdown-menu';

import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} h-full w-full`}>
      <body className="w-full">
        <NavigationMenu className="p-3 h-[55px]">
          <div className="w-full">
            <NavigationMenuList>
              <div className="flex w-full justify-between">
                <NavigationMenuItem>
                  <Link href="/" legacyBehavior passHref>
                    <NavigationMenuLink>Home</NavigationMenuLink>
                  </Link>
                </NavigationMenuItem>

                <NavigationMenuItem>
                  <DropdownMenu>
                    <DropdownMenuTrigger>
                      <CircleUserRound />
                    </DropdownMenuTrigger>

                    <DropdownMenuContent>
                      <DropdownMenuGroup>
                        <DropdownMenuItem>
                          <Link href="/profile" legacyBehavior passHref>
                            <NavigationMenuLink>Profile</NavigationMenuLink>
                          </Link>
                        </DropdownMenuItem>

                        <DropdownMenuItem>
                          <Link href="/saved-jobs" legacyBehavior passHref>
                            <NavigationMenuLink>Saved jobs</NavigationMenuLink>
                          </Link>
                        </DropdownMenuItem>

                        <DropdownMenuItem>
                          <Link href="/settings" legacyBehavior passHref>
                            <NavigationMenuLink>Settings</NavigationMenuLink>
                          </Link>
                        </DropdownMenuItem>
                      </DropdownMenuGroup>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </NavigationMenuItem>
              </div>
            </NavigationMenuList>
          </div>
        </NavigationMenu>

        {children}
      </body>
    </html>
  );
}
