import '~/styles/globals.css';

import { CircleUserRound } from 'lucide-react';

import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from '../components/ui/navigation-menu';

import { 
  Menubar,
  MenubarMenu,
  MenubarTrigger,
  MenubarContent,
  MenubarItem,
  MenubarSeparator,
  MenubarLabel,
  MenubarCheckboxItem,
  MenubarRadioGroup,
  MenubarRadioItem,
  MenubarPortal,
  MenubarSubContent,
  MenubarSubTrigger,
  MenubarGroup,
  MenubarSub,
  MenubarShortcut,
 } from '../components/ui/menubar';


import { GeistSans } from 'geist/font/sans';
import { type Metadata } from "next";
// import { DropdownMenu, DropdownMenuContent } from '@radix-ui/react-dropdown-menu';
import { DropdownMenu, DropdownMenuContent, DropdownMenuLabel, DropdownMenuTrigger, DropdownMenuSeparator, DropdownMenuGroup, DropdownMenuItem } from '~/components/ui/dropdown-menu';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} w-full h-full`}>
      <body className="w-full">
        <NavigationMenu className="p-3">
          <div className="w-full">
            <NavigationMenuList>
              <div className="flex justify-end w-full">
                <NavigationMenuItem>
                  <DropdownMenu>
                    <DropdownMenuTrigger>
                      <CircleUserRound />
                    </DropdownMenuTrigger>

                    <DropdownMenuContent>
                      <DropdownMenuGroup>
                        <DropdownMenuItem>
                          Profile
                        </DropdownMenuItem>

                        <DropdownMenuItem>
                          Saved Jobs
                        </DropdownMenuItem>

                        <DropdownMenuItem>
                          Settings
                        </DropdownMenuItem>
                      </DropdownMenuGroup>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </NavigationMenuItem>
              </div>
            </NavigationMenuList>
          </div>
        </NavigationMenu>

        {children}
      </body>
    </html>
  );
}
